---
#
# Ansible managed
#
repository:
  description: Install and configure logrotate on your system.
  homepage: https://robertdebock.nl/
  topics: logrotate, monitoring, system, ansible, molecule, tox, playbook
